project:
  type: website
  output-dir: docs

website:
  title: "Alex's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "CV"
        href: FINAL Alexander Sun Resume.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


